import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/chapter-1-fundamentals',
        'module-1-ros2/chapter-2-communication',
        'module-1-ros2/chapter-3-urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/index',
        'module-2-digital-twin/physics-simulation-gazebo',
        'module-2-digital-twin/sensor-simulation',
        'module-2-digital-twin/unity-hri-concepts',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-isaac-robot-brain/nvidia-isaac-sim-fundamentals',
        'module-3-isaac-robot-brain/isaac-ros-accelerated-perception',
        'module-3-isaac-robot-brain/nav2-humanoid-navigation',
        'module-3-isaac-robot-brain/assessment',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/voice-to-action-interfaces',
        'module-4-vla/cognitive-planning-with-llms',
        'module-4-vla/capstone-autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
